import type { Metadata } from "next";
import "./globals.css";
import HeaderNav from '@/components/header';
import { Inter } from "next/font/google";
import React from "react";
import { WalletStoreProvider } from "@/stores/useWallet";
import Providers from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

import { headers } from 'next/headers' // added


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookies = headers().get('cookie')

  return (
    <html lang="en">
      <script src="http://localhost:8097" async={true} ></script>
      <body className={`${inter.className} antialiased`} >
        <Providers cookies={cookies}>  
          <WalletStoreProvider>
            <HeaderNav />
              {children}
            </WalletStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
