import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Providers}  from "./providers";
import HeaderNav from '@/components/header';
import { config } from "@/config";
import { cookieToInitialState } from "@account-kit/core";
import { headers } from "next/headers";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initialState = cookieToInitialState(
    config,
    headers().get("cookie") ?? undefined
  );

  return (
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
            <Providers initialState={initialState}>
              <HeaderNav />
              {children}
            </Providers>
        </body>
      </html>
  );
}
